gcal/trunk/src/objects/googSession__c.object
<CustomObject>
    <description>Holds a google session id for a user and app combo</description>
    <fields>
        <fullName>AuthSubSessionToken__c</fullName>
        <inlineHelpText>The token for your authenticated session.</inlineHelpText>
        <label>AuthSubSessionToken</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>Google Auth Token</label>
    <nameField>
        <label>Token Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Google Auth Token</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

gcal/trunk/src/classes/AuthSubController.cls
public class AuthSubController {
    
    public pagereference exchangeRequestToken() {
        if ( ApexPages.currentPage().getParameters().get('token') != null) { 
            string sessToken = 
             AuthSubUtil.exchangeForSessionToken( 
                ApexPages.currentPage().getParameters().get('token'));
            // store the token 
            // this assumes a you store tokens in a custom object
            GoogSession__c session = new googSession__c(id=
                ApexPages.currentPage().getParameters().get('id'),
                 AuthSubSessionToken__c = sessToken );
            
            update session; 
        }
        return null;
    }
    
    public boolean getRequestToken() {
        return (ApexPages.currentPage().getParameters().get('token') == null
        && ApexPages.currentPage().getParameters().get('id') != null);
    }
    
    public static testMethod void t1() {   
   
        PageReference pageRef = Page.authsub;
        Test.setCurrentPage(pageRef);
  
        AuthSubController stc = new AuthSubController( );
        ApexPages.currentPage().getParameters().put('token', 'yyyy');
        ApexPages.currentPage().getParameters().put('id', 'yyyy');
        stc.exchangeRequestToken();
        stc.getRequestToken();
    }
     public static testMethod void t2() {   
   
        PageReference pageRef = Page.authsub;
        Test.setCurrentPage(pageRef);
  
        AuthSubController stc = new AuthSubController( );
        stc.getRequestToken();
        stc.exchangeRequestToken();
        
    }
}