microfinance/trunk/src/objects/Loan_Account__c.object
<CustomObject>
    <description>Used to track a Loan Account for a given client/group</description>
    <fields>
        <fullName>Annual_Interest_Rate__c</fullName>
        <label>Annual Interest Rate (ex. &quot;8.125&quot;)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Grace Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <formula>CASE(Loan_Product__r.Interest_Rate_Type__c,&apos;Flat&apos;,&apos;Flat&apos;,&apos;Declining Balance&apos;,&apos;Declining Balance&apos;,&apos;Interest Only&apos;,&apos;Interest Only&apos;,&apos;Not Defined&apos;)</formula>
        <label>Interest Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Interest_at_Disbursement__c</fullName>
        <formula>IF(NOT(ISNULL( Loan_Product__c)),IF(  Loan_Product__r.Int_Ded_Disbursement__c ,&apos;Yes&apos;,&apos;No&apos;),&apos;Not Defined&apos;)</formula>
        <label>Interest Deducted at Disbursement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Loan_Product__c</fullName>
        <description>Loan Product from which the Loan Account terms are derived.</description>
        <label>Loan Product</label>
        <referenceTo>Loan_Product__c</referenceTo>
        <relationshipLabel>Loan Accounts</relationshipLabel>
        <relationshipName>Loan_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Outstanding_Balance__c</fullName>
        <label>Outstanding Balance</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Payment_Type__c</fullName>
        <label>Payment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voucher</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Period__c</fullName>
        <label>Payment Period</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Biweekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>Today()+7</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

microfinance/trunk/src/objects/Loan_Product__c.object
<CustomObject>
    <description>The loan product defines the product attributes that are used as a basis for defining a loan account.</description>
    <fields>
        <fullName>Int_Ded_Disbursement__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Only applicable for flat interest loans. If “Interest deducted at
disbursement” is selected, grace period option will not be enabled for such
loan products. If this attribute is set to On for a product instance, the first
repayment date is the same as the loan disbursement date. Grace period is
not applicable since the repayment starts with loan disbursement.</description>
        <label>Interest Deducted at Disbursement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Interest_Rate_Type__c</fullName>
        <description>The formula used to calculate interest due, based on the amount of money borrowed. For
example, the “Flat” rate sets the interest due as the product of the principal times the
interest rate times the full term of the loan and the amount can be paid upfront or distributed
throughout the loan period. The “Declining Balance” rate charges interest on the
outstanding loan at the end of the installment period. As the loan amount decreases, the
interest due decreases as well.</description>
        <label>Interest Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Flat</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Declining Balance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Interest Only</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <description>The full date after which loans of this type may be issued.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Loan Product</label>
    <nameField>
        <label>Loan Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

microfinance/trunk/src/objects/Loan_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Balance_Adjustment__c</fullName>
        <formula>IF( $RecordType.Name = &quot;Payment&quot;, (Amount__c * -1), Amount__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Balance Adjustment</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Grace Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipName>Loan_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Paid_Date__c</fullName>
        <label>Paid Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan Transaction</label>
    <nameField>
        <displayFormat>TN-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Transactions</pluralLabel>
    <recordTypes>
        <fullName>Disbursement</fullName>
        <active>true</active>
        <description>Payment of funds to the client</description>
        <label>Disbursement</label>
    </recordTypes>
    <recordTypes>
        <fullName>Interest</fullName>
        <active>true</active>
        <description>Balance adjustment from calculated interest</description>
        <label>Interest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payment</fullName>
        <active>true</active>
        <description>Funds received from client against loan balance</description>
        <label>Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

microfinance/trunk/src/classes/LoanUtil.cls
public class LoanUtil
{   
    // TO DO convert strings to constants
 
    private Integer PRECISION = 2;
    
    private Id disbursementRecordTypeId;
    private Id interestRecordTypeId;
    private Id scheduledPaymentRecordTypeId;
    
    public LoanUtil()
    {
        disbursementRecordTypeId = MetadataUtil.getRecordTypeId('Loan_Transaction__c', 'Disbursement');
        interestRecordTypeId = MetadataUtil.getRecordTypeId('Loan_Transaction__c', 'Interest'); 
        scheduledPaymentRecordTypeId = MetadataUtil.getRecordTypeId('Loan_Transaction__c', 'Payment');
    }

    /*
     *  function generatePayments_Lookup
     */
    public void generatePayments(Loan_Account__c loanAcct)
    {    
        //Loan_Product__c p = [SELECT Id, Interest_Rate_Type__c, Int_Ded_Disbursement__c FROM Loan_Product__c WHERE Id = :loanAcct.Loan_Product__c];
    
        // ensure safe conversion
        Integer numPeriods = Math.round(Math.floor(loanAcct.Number_of_Installments__c)); 
        Double periodicInterestRate = calculatePeriodicInterestRate(loanAcct.Annual_Interest_Rate__c,
                                                                    loanAcct.Period__c);
        Double paymentAmt;
        Double interest;
        
        if(loanAcct.Interest_at_Disbursement__c == 'Yes' && loanAcct.Interest_Rate_Type__c == 'Flat'){
            paymentAmt = FinCalc.calculatePayment(0, loanAcct.Loan_Amount__c, numPeriods, loanAcct.Interest_Rate_Type__c);
            interest = FinCalc.calculateInterest(periodicInterestRate,loanAcct.Loan_Amount__c, numPeriods);
        }else{
            paymentAmt = FinCalc.calculatePayment(periodicInterestRate , loanAcct.Loan_Amount__c, numPeriods, loanAcct.Interest_Rate_Type__c);        
        }
        
        System.debug('Payment Amount = ' + paymentAmt);
        paymentAmt = decimalRound(paymentAmt, PRECISION); // TO DO get precision from currency
        
        
        //Special handling for 'Interest Only'
        if(loanAcct.Interest_Rate_Type__c == 'Interest Only'){
            interest = decimalRound(paymentAmt * numPeriods,PRECISION); 
        }else{
            interest = decimalRound(paymentAmt * numPeriods - loanAcct.Loan_Amount__c,PRECISION);
        }
        
        createAndInsertTransactionSchedule_NoCommit(
                loanAcct,
                paymentAmt,
                numPeriods,
                interest);                

        // change record type to remove button
        MetadataUtil.updateLoanAccountRecordType_NoCommit(loanAcct.Id, 'Scheduled Loan');

    } // generatePayments
    
    
    public static Double decimalRound(Double amt, Integer decimalPrecision) {      
        Double adjuster = Math.pow(10,decimalPrecision);
        return Math.ceil(amt * adjuster) / adjuster;
    }
    
    static testMethod void testDecimalRound(){
        Double amt = 58.33333333333334;
        amt = decimalRound(amt,2);
        System.assertEquals(amt,58.34);
    }
    
    public static Double calculatePeriodicInterestRate(Double annualRate,
                                                 String period)
    {
        Integer paymentsPerYear;
        if (period == 'Monthly') {
             paymentsPerYear = 12;
        } else if (period == 'Biweekly') {
             paymentsPerYear = 26;
        } else {
             // default: Weekly
             paymentsPerYear = 52;
        }
        
        System.debug('Periodicity = ' + Period + paymentsPerYear);
        
        
        return (annualRate / paymentsPerYear);
    }

    
    private void createAndInsertTransactionSchedule_NoCommit(Loan_Account__c loanAcct,
                                                             Double paymentAmt,
                                                             Integer numPeriods,
                                                             Double interest)
    {
        Loan_Transaction__c[] transactionsToAdd = new Loan_Transaction__c[0];
        
        // record disbursement
        transactionsToAdd.add(
            MetadataUtil.buildTransaction(loanAcct.Id,
                             disbursementRecordTypeId,
                             loanAcct.Loan_Amount__c,
                             loanAcct.Start_Date__c,
                             loanAcct.Payment_Type__c,
                             loanAcct.Grace_Period_Days__c) );
        // record interest                                                                      
        transactionsToAdd.add(
            MetadataUtil.buildTransaction(loanAcct.Id,
                             interestRecordTypeId,
                             interest,
                             null, // ???
                             'N/A',
                             loanAcct.Grace_Period_Days__c) );
                             
        //Special handling for interest at disbursement                     
        if(loanAcct.Interest_at_Disbursement__c == 'Yes'){
            transactionsToAdd.add(
            MetadataUtil.buildTransaction(loanAcct.Id,
                             scheduledPaymentRecordTypeId,
                             interest,
                             loanAcct.Start_Date__c,
                             loanAcct.Payment_Type__c,
                             0) );        
        }
        
            // generate payments
        for (Integer i=0; i < numPeriods; i++) {
            transactionsToAdd.add(
                MetadataUtil.buildTransaction(loanAcct.Id,
                                  scheduledPaymentRecordTypeId,
                                  paymentAmt,
                                  calculateDueDate(loanAcct.Start_Date__c,
                                                   loanAcct.Period__c,
                                                   i+1),
                                  loanAcct.Payment_Type__c,
                                  loanAcct.Grace_Period_Days__c) );
        }  
        
         if(loanAcct.Interest_at_Disbursement__c == 'Yes' && loanAcct.Interest_Rate_Type__c == 'Flat'){
            //generate principal payment to coincide with last interest payment
            transactionsToAdd.add(
                MetadataUtil.buildTransaction(loanAcct.Id,
                                  scheduledPaymentRecordTypeId,
                                  loanAcct.Loan_Amount__c,
                                  calculateDueDate(loanAcct.Start_Date__c,
                                                   loanAcct.Period__c,
                                                   numPeriods),
                                  loanAcct.Payment_Type__c,
                                  loanAcct.Grace_Period_Days__c) );
        
        }
        insert transactionsToAdd;
    }
    
    
    /*
     *  function getDueDate
     *
     *  calculate the due date for a given payment number
     *  - startDate is the date of the disbursement (first payment is due one period after disbursement)
     *  - periodType is 'Monthly', 'Biweekly', or 'Weekly' -- time between payments
     *  - periodNumber is the 1-based index of payment periods
     */
    public static Date calculateDueDate(Date startDate, String periodType, Integer periodNum)
    {
        Date dueDate;
        if (periodType == 'Monthly') {
            dueDate = startDate.addMonths(1 * periodNum);
        } else if (periodType == 'Biweekly') {
            dueDate = startDate.addDays(14 * periodNum);
        } else {
            // default: Weekly
            dueDate = startDate.addDays(7 * periodNum);
        }
        return dueDate;
    } // calculateDueDate
    

    /*
     *  calculateTransactionsSum
     */
    private Double calculateTransactionsSum(Id loanAcctId)
    {
        Double sum = 0;
        for ( Loan_Transaction__c loanTransaction:
                 [SELECT Balance_Adjustment__c
                  FROM Loan_Transaction__c
                  WHERE Loan_Account__c = :loanAcctId
                        AND (Type__c = 'N/A' OR Paid_Date__c != null)])
        {
            sum += loanTransaction.Balance_Adjustment__c;
        }
        return sum;
    } // calculateTransactionsSum


    /*
     *    updateOutstandingBalance_NoCommit
     *    (for use within a trigger)
     */
    public Double updateOutstandingBalance_NoCommit(Id loanAcctId)
    {
        Double sum = calculateTransactionsSum(loanAcctId);

        Loan_Account__c loanAcct = new Loan_Account__c(
            Id = loanAcctId,
            Outstanding_Balance__c = sum
            );
        update loanAcct;
        return sum;
    } // updateOutstandingBalance_NoCommit

} // package