microfinance/trunk/src/objects/Loan_Account__c.object
<CustomObject>
    <description>Used to track a Loan Account for a given client/group</description>
    <fields>
        <fullName>Grace_Period_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Grace Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

microfinance/trunk/src/objects/Loan_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Grace_Period_Days__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Grace Period (Days)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipName>Loan_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Cash</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Check</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Voucher</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Loan Transaction</label>
    <nameField>
        <displayFormat>TN-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

microfinance/trunk/src/classes/MetadataUtil.cls
public class MetadataUtil
{
	public static Id getRecordTypeId(String objectType, String recordTypeName) {
    	return [SELECT Id FROM RecordType WHERE SobjectType = :objectType AND Name = :recordTypeName LIMIT 1].Id;
	}
   
    /**
  	 *  function updateLoanRecordType_NoCommit
  	 */
  	public static void updateLoanAccountRecordType_NoCommit(Id id, String recordTypeName) {
  		Id updateRecordTypeId = getRecordTypeId('Loan_Account__c', recordTypeName);

		Loan_Account__c updateObj = new Loan_Account__c(
        		Id = id,
			RecordTypeId = updateRecordTypeId
			);
    		update updateObj;  		
	}

	public static Loan_Transaction__c buildTransaction(Id loanAcctId,
  												Id recordTypeId,
  												Double amount,
  												Date dueDate,
  												String paymentType,
                                                Double gracePeriod)
	{
		return new Loan_Transaction__c(
			Loan_Account__c = loanAcctId,
			RecordTypeId = recordTypeId,
			Amount__c = amount,
			Due_Date__c = dueDate,
			Type__c = paymentType,
			Grace_Period_Days__c = gracePeriod
			); 		
  	}
}