microfinance/trunk/src/objects/Loan_Account__c.object
<CustomObject>
    <description>Used to track a Loan Account for a given client/group</description>
    <fields>
        <fullName>Annual_Interest_Rate__c</fullName>
        <label>Annual Interest Rate (ex. &quot;8.125&quot;)</label>
        <precision>5</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Installments__c</fullName>
        <label>Number of Installments</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Loan Account</label>
    <nameField>
        <displayFormat>LN-{00000000}</displayFormat>
        <label>Loan ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Accounts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

microfinance/trunk/src/objects/Loan_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Loan_Account__c</fullName>
        <label>Loan Account</label>
        <referenceTo>Loan_Account__c</referenceTo>
        <relationshipName>Loan_Transaction</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Paid_Date__c</fullName>
        <label>Paid Date</label>
        <type>Date</type>
    </fields>
    <label>Loan Transaction</label>
    <nameField>
        <displayFormat>TN-{000000000}</displayFormat>
        <label>Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loan Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

microfinance/trunk/src/classes/ServiceMethods.cls
global class ServiceMethods
{

  /*
   *   updateOutstandingBalance
   */
  webService static Double updateOutstandingBalance(Id loanAcctId) {
    LoanUtil loanUtil = new LoanUtil();
    Double sum = loanUtil.updateOutstandingBalance_NoCommit(loanAcctId);
    return sum;
  } // updateOutstandingBalance


  /*
   *   generatePaymentSchedule
   */
  webService static void generatePaymentSchedule(Id loanAcctId) {

    Loan_Account__c loanAcct =
             [select Id, Loan_Amount__c, Annual_Interest_Rate__c, Number_of_Installments__c
              from Loan_Account__c
              where Id = :loanAcctId];

    if (loanAcct != null) {
        LoanUtil loanUtil = new LoanUtil();
        loanUtil.generatePayments(loanAcct);
    } else {
      // TO DO throw exception
   }
  } // generatePaymentSchedule

  webService static void markPaid(Id[] loanTransactionIds)
  {
      Date d = System.today();
      Loan_Transaction__c[] transactionsToUpdate = new Loan_Transaction__c[0];
      for (Id loanTransId : loanTransactionIds) {
          transactionsToUpdate .add( new Loan_Transaction__c(Id = loanTransId, Paid_Date__c = d) );
      }
      update transactionsToUpdate;
  }

}