microfinance/trunk/src/objects/Savings_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <formula>Total_Deposits__c +  Total_Interest__c -  Total_Withdrawals__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Activation_Date__c</fullName>
        <label>Activation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Annual_Interest_Rate__c</fullName>
        <formula>Savings_Product__r.Interest_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Annual Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Interest_Rate_Calculation_Frequency__c</fullName>
        <formula>CASE( Savings_Product__r.Interest_Rate_Calculation_Frequncy__c ,&apos;Weekly&apos;,&apos;Weekly&apos;, &apos;Biweekly&apos;, &apos;Biweekly&apos;,&apos;Monthly&apos;,&apos;Monthly&apos;,&apos;Not Defined&apos;)</formula>
        <label>Interest Rate Calculation Frequency</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Min_Balance_For_Interest__c</fullName>
        <formula>Savings_Product__r.Min_Balance_for_Interest__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Min Balance For Interest</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Refer to http://www.mifos.org/knowledge/functional-specifications/account-creation/savings-accounts for explanation of various status values.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Application</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Savings Account</label>
    <nameField>
        <label>Savings Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Savings Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

microfinance/trunk/src/objects/Savings_Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <formula>Savings_Account__r.Account_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Current Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Savings_Account__c</fullName>
        <label>Savings Account</label>
        <referenceTo>Savings_Account__c</referenceTo>
        <relationshipLabel>Savings Transactions</relationshipLabel>
        <relationshipName>Savings_Transactions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Unscheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overdue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Calculating</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Transaction Date</label>
        <type>Date</type>
    </fields>
    <label>Savings Transaction</label>
    <nameField>
        <displayFormat>TN-{000000000}</displayFormat>
        <label>Savings Transaction ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Savings Transactions</pluralLabel>
    <recordTypes>
        <fullName>Deposit</fullName>
        <active>true</active>
        <description>Deposit</description>
        <label>Deposit</label>
    </recordTypes>
    <recordTypes>
        <fullName>Interest</fullName>
        <active>true</active>
        <description>Interest</description>
        <label>Interest</label>
    </recordTypes>
    <recordTypes>
        <fullName>Withdrawal</fullName>
        <active>true</active>
        <description>Withdrawal</description>
        <label>Withdrawal</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

microfinance/trunk/src/classes/SavingsUtil.cls
public class SavingsUtil{
    private Integer PRECISION = 2; 
    
    public Id depositRecordTypeId;
    public Id interestRecordTypeId;
    public Id withdrawalRecordTypeId;
    
    public SavingsUtil(){
        depositRecordTypeId = MetadataUtil.getRecordTypeId('Savings_Transaction__c', 'Deposit');
        interestRecordTypeId = MetadataUtil.getRecordTypeId('Savings_Transaction__c', 'Interest');
        withdrawalRecordTypeId = MetadataUtil.getRecordTypeId('Savings_Transaction__c', 'Withdrawal');
    }

    public void postInterest(List<Savings_Transaction__c> transactions){
        List<Savings_Transaction__c> inserts = new List<Savings_Transaction__c>(); 
        
        Set<Id> accountIds = new Set<Id>();

        for (Integer i = 0; i < transactions.size(); i++) {
            accountIds.add(transactions[i].Savings_Account__c);
        }

        Map<Id, Savings_Account__c> accts = new Map<Id, Savings_Account__c>(
                           [select Id,Min_Balance_For_Interest__c,Status__c, Activation_Date__c,Account_Balance__c,Interest_Rate_Calculation_Frequency__c,Annual_Interest_Rate__c from Savings_Account__c where id in :accountIds]);
        
        for(Savings_Transaction__c t : transactions){
            Savings_Account__c a = accts.get(t.Savings_Account__c);    
            
            //Verify eligible for interest calculation
            if(a != null && eligibleForInterest(t,a)){
                
                //Post new transaction for interest                
                inserts.add(getInterestTransaction(t,a));                             
            }    
            
            //Revert 'calculating' transaction to 'scheduled' and update with appropriate date 
            Savings_Transaction__c s = t.clone(false,true);
            s.Status__c = 'Scheduled';          
            s.Due_Date__c = LoanUtil.calculateDueDate(s.Due_Date__c, a.Interest_Rate_Calculation_Frequency__c, 1);
            inserts.add(s);
            
            //TODO: Figure out what to do with unscheduled
            t.Status__c = 'Unscheduled';  
            t.Due_Date__c = s.Due_Date__c;          
        }
        
        //TODO: Take care of more than 200 inserts
        if(inserts.size() > 0) insert inserts;
    }
    
    private boolean eligibleForInterest(Savings_Transaction__c t, Savings_Account__c a){
        return 'Active'.equals(a.Status__c) 
                && getBalance(t,a) >= a.Min_Balance_For_Interest__c
                && a.Activation_Date__c != null  && a.Activation_Date__c.daysBetween(Date.today()) >= 0;
    }
    
    private Savings_Transaction__c getInterestTransaction(Savings_Transaction__c t,Savings_Account__c a){
        //Id should not be same. Deep clone because different objects.
        Savings_Transaction__c interest = t.clone(false,true);        
        interest.Status__c = 'Complete';
        interest.Transaction_Date__c = Date.today();
        
        //Calculate and update interest
        Double periodicInterestRate = LoanUtil.calculatePeriodicInterestRate(a.Annual_Interest_Rate__c,
                                                                    a.Interest_Rate_Calculation_Frequency__c);
        
        Double interestAmt = FinCalc.calculateInterest(periodicInterestRate,getBalance(t,a),getPeriodFraction(t,a)); 
        interestAmt = LoanUtil.decimalRound(interestAmt, PRECISION);   
        interest.Amount__c = interestAmt;                                                       
        
        return interest;      
    }
    
    //TODO: Add support for multiple balance types
    private Double getBalance(Savings_Transaction__c t,Savings_Account__c a){
        return a.Account_Balance__c;
    }
        
    //TODO: Based on Activation date, figure out if the interest calculation applies to only a fraction of the period    
    private Double getPeriodFraction(Savings_Transaction__c t,Savings_Account__c a){
        return 1.0;
    }
}