sprint2010/project1/src/objects/Account.object
<CustomObject>
</CustomObject>

trunk/relationships/src/objects/Account.object
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>

affilitations/src/objects/Account.object
    <recordTypes>
        <fullName>test</fullName>
        <active>true</active>
        <label>test</label>
    </recordTypes>

sprint2010/project4/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Household__c</fullName>
        <label>Household</label>
        <referenceTo>Household__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SystemAccountProcessor__c</fullName>
        <label>_SYSTEM: ACCOUNT PROCESSOR</label>
        <picklist>
            <picklistValues>
                <fullName>One-to-One</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SystemHouseholdProcessor__c</fullName>
        <label>_SYSTEM: HOUSEHOLD PROCESSOR</label>
        <picklist>
            <picklistValues>
                <fullName>All Individual Contacts</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>All New or Edited Contacts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Contacts</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

trunk/affilitations/src/objects/Contact.object
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <label>Individual</label>
    </recordTypes>

sprint2010/project1/src/objects/Household__c.object
<CustomObject>
    <description>Physical mailing address for grouping contacts</description>
    <label>Household</label>
    <nameField>
        <label>Household Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Households</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sprint2010/project4/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>systemHouseholdContactRoleProcessor__c</fullName>
        <label>_SYSTEM: HOUSEHOLD CONTACT ROLEPROCESSOR</label>
        <picklist>
            <picklistValues>
                <fullName>All Opportunities</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No Opportunities</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

sprint2010/project5/src/classes/TEST_HouseholdOpportunity.cls
@isTest
private class TEST_HouseholdOpportunity {
	
	static testMethod void HouseholdOpportunity() {
  		HouseholdOpportunity testHouseholdOpportunity = new HouseholdOpportunity();
	}
	//test for individual account model
	
	static testMethod void opportunityWithHousehold() {
		
    	String householdContactRolesOn = system.label.Household_Contact_Role_Processor_On;  
  		//create contact
  		String newContactfirstName = 'test';
    	String newContactLastName = 'Contact_forTests';
        Contact con = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	SystemAccountProcessor__c = 'One-to-One'
        );
        insert con;
        Contact[] createdContacts = [select AccountId,Household__c from Contact where id=:con.id];
        Id accountId = createdContacts[0].AccountId;
        Id householdId = createdContacts[0].Household__c;
  		//create household member
  		Contact con2 = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	household__c = householdId
        );
        insert con2;
  		//create opportunity
  		Opportunity o = new Opportunity(
  			Name='test oppty',
  			CloseDate=date.newInstance(2001,12,12),
  			StageName='Closed Won',
  			Amount=100,
  			AccountId=accountId,
  			systemHouseholdContactRoleProcessor__c = householdContactRolesOn
  		);
		insert o;
  		//check for contact roles
  		List<OpportunityContactRole> createdRoles = [select Role, ContactId, IsPrimary from OpportunityContactRole where OpportunityId = :o.id order by ContactId];
  		system.AssertEquals(2,createdRoles.size());
  		system.AssertEquals('Donor',createdRoles[0].Role);
  		system.Assert(createdRoles[0].IsPrimary);
  		system.AssertEquals('Household Credit',createdRoles[1].Role);
	}
	/*
	static testMethod void opportunityWithHouseholdBucket() {
		
    	String householdContactRolesOn = system.label.Household_Contact_Role_Processor_On;  
  		//create contact
  		String newContactfirstName = 'test';
    	String newContactLastName = 'Contact_forTests';
        Contact con = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	SystemAccountProcessor__c = 'Individual'
        );
        insert con;
        Contact[] createdContacts = [select AccountId,Household__c from Contact where id=:con.id];
        Id accountId = createdContacts[0].AccountId;
        Id householdId = createdContacts[0].Household__c;
  		//create household member
  		Contact con2 = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	household__c = householdId
        );
        insert con2;
  		//create opportunity
  		Opportunity o = new Opportunity(
  			Name='test oppty',
  			CloseDate=date.newInstance(2001,12,12),
  			StageName='Closed Won',
  			Amount=100,
  			AccountId=accountId,
  			systemHouseholdContactRoleProcessor__c = householdContactRolesOn
  		);
		insert o;
		
  		//check for contact roles
  		List<OpportunityContactRole> createdRoles = [select Role, ContactId, IsPrimary from OpportunityContactRole where OpportunityId = :o.id order by ContactId];
  		system.AssertEquals(2,createdRoles.size());
  		system.AssertEquals('Donor',createdRoles[0].Role);
  		system.Assert(createdRoles[0].IsPrimary);
  		system.AssertEquals('Household Credit',createdRoles[1].Role);
	}
	*/
	static testMethod void opportunityWithHouseholdNoRoles() {
		  	
    	String householdContactRolesOff = system.label.Household_Contact_Role_Processor_Off;
  		//create contact
  		String newContactfirstName = 'test';
    	String newContactLastName = 'Contact_forTests';
        Contact con = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	SystemAccountProcessor__c = 'One-to-One'
        );
        insert con;
        Contact[] createdContacts = [select AccountId,Household__c from Contact where id=:con.id];
        Id accountId = createdContacts[0].AccountId;
        Id householdId = createdContacts[0].Household__c;
  		//create household member
  		Contact con2 = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	household__c = householdId
        );
        insert con2;
  		//create opportunity
  		Opportunity o = new Opportunity(
  			Name='test oppty',
  			CloseDate=date.newInstance(2001,12,12),
  			StageName='Closed Won',
  			Amount=100,
  			AccountId=accountId,
  			systemHouseholdContactRoleProcessor__c = householdContactRolesOff
  		);
		insert o;
  		//check for contact roles
  		List<OpportunityContactRole> createdRoles = [select Role, ContactId, IsPrimary from OpportunityContactRole where OpportunityId = :o.id order by ContactId];
  		system.AssertEquals(0,createdRoles.size());
	}
	static testMethod void opportunityWithNoHousehold() {
		
    	String householdContactRolesOn = system.label.Household_Contact_Role_Processor_On;  
  		//create contact
  		String newContactfirstName = 'test';
    	String newContactLastName = 'Contact_forTests';
        Contact con = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'None',
        	SystemAccountProcessor__c = 'One-to-One'
        );
        insert con;
        Contact[] createdContacts = [select AccountId,Household__c from Contact where id=:con.id];
        Id accountId = createdContacts[0].AccountId;
        Id householdId = createdContacts[0].Household__c;
  		//create household member
  		Contact con2 = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts'
        );
        insert con2;
  		//create opportunity
  		Opportunity o = new Opportunity(
  			Name='test oppty',
  			CloseDate=date.newInstance(2001,12,12),
  			StageName='Closed Won',
  			Amount=100,
  			AccountId=accountId,
  			systemHouseholdContactRoleProcessor__c = householdContactRolesOn
  		);
		insert o;
  		//check for contact roles
  		List<OpportunityContactRole> createdRoles = [select Role, ContactId, IsPrimary from OpportunityContactRole where OpportunityId = :o.id order by ContactId];
  		system.AssertEquals(0,createdRoles.size());
	}
	static testMethod void opportunityRegularAccount() {
		String householdContactRolesOn = system.label.Household_Contact_Role_Processor_On;
  		//create contact
  		Account acct = new Account(
        	Name = 'fake account'
        );
        insert acct;
  		Id accountId = acct.Id;
  		String newContactfirstName = 'test';
    	String newContactLastName = 'Contact_forTests';
        Contact con = new Contact(
        	FirstName=newContactfirstName,
        	LastName=newContactLastName,
        	SystemHouseholdProcessor__c = 'All New or Edited Contacts',
        	accountId = accountId
        );
        insert con;
        Contact[] createdContacts = [select AccountId,Household__c from Contact where id=:con.id];
        
        Id householdId = createdContacts[0].Household__c;
  		
  		//create opportunity
  		Opportunity o = new Opportunity(
  			Name='test oppty',
  			CloseDate=date.newInstance(2001,12,12),
  			StageName='Closed Won',
  			Amount=100,
  			AccountId=accountId,
  			systemHouseholdContactRoleProcessor__c = householdContactRolesOn
  		);
		insert o;
  		//check for contact roles
  		List<OpportunityContactRole> createdRoles = [select Role, ContactId, IsPrimary from OpportunityContactRole where OpportunityId = :o.id order by ContactId];
  		system.AssertEquals(0,createdRoles.size());
	}
	
	
}