contactsandorgs/trunk/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>SYSTEMIsIndividual__c</fullName>
        <defaultValue>false</defaultValue>
        <label>_SYSTEM: IsIndividual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SYSTEM_AccountType__c</fullName>
        <inlineHelpText>System field: do not use or change.</inlineHelpText>
        <label>_SYSTEM: AccountType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
</CustomObject>

contactsandorgs/branches/development/src/objects/Account.object
    <recordTypes>
        <fullName>Individual</fullName>
        <active>true</active>
        <description>Accounts used for One-to-One mappings with Contacts</description>
        <label>Individual</label>
    </recordTypes>

contactsandorgs/trunk/src/classes/IndividualAccounts_Utils.cls
public class IndividualAccounts_Utils {
    /// <name> triggerAction </name>
    /// <summary> contains possible actions for a trigger </summary>
    public enum triggerAction {beforeInsert, beforeUpdate, beforeDelete, afterInsert, afterUpdate, afterDelete, afterUndelete}
    
    public static Id IndividualAccountId; 
    
    //variable for Account Name
	private static String IndividualAccountName = Constants.BUCKET_ACCOUNT_NAME;

	public static id GetIndividualAccountId () {
	
		// look up the ID if we haven't already done it
		if ( IndividualAccountId == null ) {
			List<Account> acct = [select id,SYSTEMISINDIVIDUAL__c,SYSTEM_AccountType__c from account where Name =:IndividualAccountName LIMIT 1];
			if(acct.size()>0){
				
				if(acct[0].SYSTEMISINDIVIDUAL__c==false || acct[0].SYSTEM_AccountType__c<>Constants.BUCKET_ORGANIZATION_TYPE){
					acct[0].SYSTEMISINDIVIDUAL__c = true;
					acct[0].SYSTEM_AccountType__c = Constants.BUCKET_ORGANIZATION_TYPE;
				}
				update acct[0];
				
				IndividualAccountId = acct[0].id;	
			}			
		}
		return IndividualAccountId;
	}
	
	public static Id setIndividualAccountForTests(String accountName) {
		//create a fake Individual Account for tests

		Account individualAccountForTests = new Account(
			Name=accountName,
   	        SYSTEMISINDIVIDUAL__c = true,
   	        SYSTEM_AccountType__c = Constants.BUCKET_ORGANIZATION_TYPE
		);
		
		insert individualAccountForTests;
		
		Constants.BUCKET_ACCOUNT_NAME = accountName;
		IndividualAccountName = accountName;
		
		return individualAccountForTests.id;
		
	}
    
}